x-service: &common-dev-test
  build:
    context: .
    target: build
  working_dir: /src
  volumes:
    - .:/src
  env_file:
    - .env

version: "3.6"
services:
  prod:
    image: dhis2/im-inspector:${IMAGE_TAG:-latest}
    build: .
    env_file:
      - .env

  test:
    command: /bin/sh -c 'go test -v ./...'
    <<: *common-dev-test
