x-service: &common-dev-test
  build:
    context: .
    target: build
  working_dir: /src
  volumes:
    - .:/src
  env_file:
    - .env

version: "3.6"
services:
  prod:
    image: dhis2/im-inspector:${IMAGE_TAG:-latest}
    build: .
    env_file:
      - .env
    volumes:
      - ./k3s.yaml:/kubernetes/config

  test:
    command: /bin/sh -c 'go test -v ./...'
    <<: *common-dev-test

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  database:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - instance-manager-database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  kubernetes-init:
    build:
      dockerfile: Dockerfile.init
    volumes:
      - kubernetes-config:/tmp/kubernetes:z
      - ./scripts/init-local.sh:/scripts/init-local.sh
    command: /scripts/init-local.sh
    env_file:
      - .env

  kubernetes:
    image: rancher/k3s:v1.21.3-k3s1
    privileged: true
    command: server
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "6443:6443"
      - "443:443"
      - "80:80"
    volumes:
      - ./k3s-storage:/var/lib/rancher/k3s/storage:Z
      - kubernetes-config:/tmp/kubernetes:z
    environment:
      K3S_KUBECONFIG_OUTPUT: /tmp/kubernetes/k3s.yaml
      K3S_KUBECONFIG_MODE: 666

volumes:
  instance-manager-database: { }
  kubernetes-config: { }
