apiVersion: skaffold/v2beta21
kind: Config
build:
  artifacts:
    - image: dhis2/instance-inspector
deploy:
  helm:
    releases:
      - name: instance-inspector-feature
        namespace: instance-manager-feature
        chartPath: helm/chart
        artifactOverrides:
          imageRepository: dhis2/instance-inspector
        useHelmSecrets: true
        valuesFiles:
          - helm/data/secrets/feature/instance-inspector.yaml
          - helm/data/values/feature/instance-inspector.yaml
        # TODO: Retrieve feature tag from env - https://skaffold.dev/docs/references/yaml/#deploy-helm-releases-setValueTemplates
        setValues:
          rabbitMq.host: rabbitmq-snapshot.instance-manager-feature.svc.cluster.local
