apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: im-inspector
build:
  artifacts:
    - image: dhis2/im-inspector
  tagPolicy:
    inputDigest: { }
deploy:
  helm:
    releases:
      - name: im-inspector-{{ .ENVIRONMENT }}
        namespace: instance-manager-{{ .CLASSIFICATION }}
        chartPath: helm/chart
        setValueTemplates:
          imageRepository: dhis2/im-inspector
          serviceAccount:
            annotations:
              "eks\\.amazonaws\\.com\\/role-arn": arn:aws:iam::767224633206:role/instance-cluster-test-im-inspector-{{ .CLASSIFICATION }}
          rabbitMq:
              host: im-rabbitmq-{{ .ENVIRONMENT }}.instance-manager-{{ .CLASSIFICATION }}.svc
        useHelmSecrets: true
        valuesFiles:
          - helm/data/secrets/{{ .CLASSIFICATION }}/values.yaml
          - helm/data/values/{{ .CLASSIFICATION }}/values.yaml

      - name: im-rabbitmq-{{ .ENVIRONMENT }}
        namespace: instance-manager-{{ .CLASSIFICATION }}
        createNamespace: true
        remoteChart: rabbitmq
        repo: https://charts.bitnami.com/bitnami
        version: 10.3.9
        useHelmSecrets: true
        valuesFiles:
          - helm/data/secrets/{{ .CLASSIFICATION }}/rabbitmq.yaml

# TODO should we use empty profiles to conform to the instance-manager reusable workflow or have a conditional in the workflow Deploy step (`if repo is im-manager ...`)?
profiles:
  - name: dev
  - name: prod
