apiVersion: skaffold/v2beta25
kind: Config
build:
  artifacts:
    - image: dhis2/instance-inspector
deploy:
  helm:
    releases:
      - name: im-inspector-{{ .ENVIRONMENT }}
        namespace: instance-manager-{{ .ENVIRONMENT }}
        chartPath: helm/chart
        artifactOverrides:
          imageRepository: dhis2/instance-inspector
        useHelmSecrets: true
        valuesFiles:
          - helm/data/secrets/{{ .ENVIRONMENT }}/values.yaml
          - helm/data/values/{{ .ENVIRONMENT }}/values.yaml

      - name: im-rabbitmq-{{ .ENVIRONMENT }}
        namespace: instance-manager-{{ .ENVIRONMENT }}
        createNamespace: true
        remoteChart: rabbitmq
        repo: https://charts.bitnami.com/bitnami
        #        version: ???
        useHelmSecrets: true
        valuesFiles:
          - helm/data/secrets/{{ .ENVIRONMENT }}/rabbitmq.yaml
