// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/dhis2-sre/im-inspector/pgk/config"
	"github.com/dhis2-sre/im-inspector/pgk/handler"
	"github.com/dhis2-sre/im-inspector/pgk/inspector"
	"github.com/dhis2-sre/rabbitmq/pgk/queue"
)

// Injectors from wire.go:

func GetEnvironment() Environment {
	configuration := config.ProvideConfiguration()
	v := ProvideHandlers(configuration)
	inspectorInspector := inspector.ProvideInspector(v, configuration)
	environment := ProvideEnvironment(inspectorInspector, v)
	return environment
}

// wire.go:

type Environment struct {
	Inspector inspector.Inspector
	Handlers  []handler.PodHandler
}

func ProvideEnvironment(inspector2 inspector.Inspector, handlers []handler.PodHandler) Environment {
	return Environment{inspector2, handlers}
}

func ProvideHandlers(configuration config.Configuration) []handler.PodHandler {
	producer := queue.ProvideProducer(configuration.RabbitMq.GetUrl())
	return []handler.PodHandler{handler.ProvideTTLDestroyHandler(&producer), handler.ProvideTTLWarningHandler(&producer), handler.ProvideIdHandler()}
}
