apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "instance-inspector.fullname" . }}
  labels:
  {{- include "instance-inspector.labels" . | nindent 4 }}
data:
  DEPLOYABLE_NAMESPACES: {{ join "," .Values.deployableNamespaces | quote }}
