{{- $root := . -}}
{{ range $namespace := .Values.deployableNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "instance-inspector.fullname" $root }}
  namespace: {{ $namespace }}
  labels:
  {{- include "instance-inspector.labels" $root | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "instance-inspector.serviceAccountName" $root }}
    namespace: {{ $root.Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "instance-inspector.fullname" $root }}
  apiGroup: rbac.authorization.k8s.io
---
{{ end }}
