{{- $root := . -}}
{{ range $namespace := .Values.deployableNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "im-inspector.fullname" $root }}
  namespace: {{ $namespace }}
  labels:
  {{- include "im-inspector.labels" $root | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
---
{{ end }}
