kind: Secret
apiVersion: v1
metadata:
  name: {{ include "im-inspector.fullname" . }}
  labels:
  {{- include "im-inspector.labels" . | nindent 4 }}
type: Opaque
data:
  RABBITMQ_HOST: {{ .Values.rabbitMq.host | b64enc }}
  RABBITMQ_PORT: {{ .Values.rabbitMq.port | toString | b64enc }}
  RABBITMQ_USERNAME: {{ .Values.rabbitMq.username | b64enc }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitMq.password | b64enc }}
